version: '3'

services:

  db:
    image: kartoza/postgis
    environment: 
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=gisuser
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=gis
      - POSTGRES_PORT=5432
    # ports:
    #   - "5432:5432"
    

