version: '3'

services:

  web:
    build: backend/
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/geospatialDataHub/backend
    #depends_on:
      #- db
    ports:
      - "8000:8000"

  client:
    build: frontend/
    command: yarn run serve
    volumes:
      - .:/code/geospatialDataHub/frontend
    depends_on:
      - web
      #- db
    # environment:
    #   DB_URL: db:5432
    ports:
      - "8080:8080"

  db:
    build: database/
    volumes:
      - .:/code/geospatialDataHub/database
    ports:
      - "5432:5432"


  # db:
  #   image: kartoza/postgis
  #   environment: 
  #     - ALLOW_IP_RANGE=0.0.0.0/0
  #     - POSTGRES_USER=gisuser
  #     - POSTGRES_PASS=password
  #     - POSTGRES_DBNAME=gis
  #     - POSTGRES_PORT=5432


    # ports:
    #   - "5432:5432"
    

