version: '3'

services:
  db:
    image: postgres
  web:
    build: backend/
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/geospatialDataHub/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build: frontend/
    command: yarn run serve
    volumes:
      - .:/code/geospatialDataHub/frontend
    depends_on:
      - web
    ports:
      - "8080:8080"