version: '3'

services:
  db:
    image: postgres
  web:
    build: backend/
    command: python3 manage.py runserver 0.0.0.0:8990
    volumes:
      - .:/code/geospatialDataHub/backend
    ports:
      - "8990:8990"
    depends_on:
      - db